// Generated by CoffeeScript 1.3.3
(function() {
  'use strict';

  this.MyCtrl1 = function() {};

  this.MyCtrl1.$inject = [];

  this.MyCtrl2 = function() {};

  this.MyCtrl2.$inject = [];

}).call(this);
